const mongoose=require('mongoose');

const DonationSchema=new mongoose.Schema({
    ngoId:{
        type:String,
        required:false
    },
    ngoName:{
        type:String,
        required:false
    },
    ngoEmail:{
        type:String,
        required:false
    },
    ngoContactNumber:{
        type:String,
        required:false
    },
    riderName:{
        type:String,
        required:false
    },
    riderContact:{
        type:String,
        required:false
    },

    donorEmail:{
        type:String,
        required:true
    },
    donorContactNumber:{
        type:String,
        required:true
    },
    donorId:{
        type:String,
        required:true
    },
    donorName:{
        type:String,
        required:true
    },
    donorDp:{
        type:String,
        required:false
    },
    donationCategory:{
        type:String,
        required:true
    },
    donationStatus:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    donationDate:{
        type:Date,
        default:Date.now
    },
    donation:{
        type:Object,
        required:true
    },
})

module.exports=mongoose.model('Donation',DonationSchema)