import { Ionicons } from "@expo/vector-icons";
import ColorPallete from "../constants/ColorPallete";

export const Donors = [
    {
        id: '0001',
        name: 'Elizabeth',
        category: 'Food',
        time: '5m ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1573165850883-9b0e18c44bd2?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0002',
        name: 'Mark Jr.',
        category: 'Medicine',
        time: '30m ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0003',
        name: 'Lois Saint',
        category: 'Ration',
        time: '1h ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0004',
        name: 'Catherine',
        category: 'Food',
        time: '1h ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1573165850883-9b0e18c44bd2?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0005',
        name: 'Samantha',
        category: 'Medicine',
        time: '2h ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1573165850883-9b0e18c44bd2?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0006',
        name: 'William J.',
        category: 'Medicine',
        time: '2h ago',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
]

export const NOTIFICATIONS = [
    {
        id: '23342dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Alexa',
        desc: 'has donated to food donations.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '26342dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Mark',
        desc: 'has donated Rs. 5000.',
        icon: <Ionicons name='md-wallet-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23352dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Your',
        desc: 'account has been Verified.',
        icon: <Ionicons name='shield-checkmark-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '20342dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Brian',
        desc: 'has donated medicines.',
        icon: <Ionicons name='medkit-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23346dfsdmsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23346dxsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '2334hdfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23346dvsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '83346dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '21346dfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23346lfsdfsdf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },
    {
        id: '23346dfsdfssf',
        recieverId: 'sdadasdwer324234ertf',
        name: 'Samantha',
        desc: 'donated Chicken Biryani.',
        icon: <Ionicons name='fast-food-outline' size={18} color={ColorPallete.darkBlue} />,
        time: '2 min',
        status: 'unread',
        read: false,
    },

]

export const DonationList = [
    {
        id: '0001',
        food: 'Biryani',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=1788&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://plus.unsplash.com/premium_photo-1694141253763-209b4c8f8ace?q=80&w=2069&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1691171047462-66025ecd5efc?q=80&w=1911&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0002',
        food: 'Samosa',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1601050690294-397f3c324515?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1589301773859-bb024d3ad558?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0003',
        food: 'Pasta',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1611270629569-8b357cb88da9?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1600803907087-f56d462fd26b?q=80&w=1854&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1627286400579-027de47e9e73?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
    {
        id: '0004',
        food: 'Mangoes',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!. Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda autem ducimus ipsum at, voluptatibus eum repellendus voluptatum, est iure eveniet esse! Unde dicta dolorum adipisci quasi quis odit temporibus. Amet!.',
        contact: {
            phone: '+9234567890',
            city: 'Lahore',
            country: 'Pakistan',
        },
        images: [
            'https://images.unsplash.com/photo-1519096845289-95806ee03a1a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1628695323145-5be0b8fde365?q=80&w=1852&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'https://images.unsplash.com/photo-1629637272678-9b0d5a41b1e5?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ],
    },
]

export const Subscriber = [
        {
            id: '0001',
            name: 'Eesha',
            images: [
                'https://images.unsplash.com/photo-1573165850883-9b0e18c44bd2?q=80&w=1888&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            amount: '10000',
            type: 'Yearly',
        },
        {
            id: '0002',
            name: 'Sohaib',
            images: [
                'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            amount: '5000',
            type: 'Monthly',
        },
        {
            id: '0003',
            name: 'Soban',
            images: [
                'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            amount: '500',
            type: 'Weekly',
        },
        {
            id: '0004',
            name: 'Ahmed',
            images: [
                'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1530490125459-847a6d437825?q=80&w=1785&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'https://images.unsplash.com/photo-1636202339022-7d67f7447e3a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            ],
            amount: '800000',
            type: 'Yearly',
        },

]